### ISSUE TITLE
Docker hub integration

### ISSUE THREAD

**Issue by gnokoheat** [taehoio/youtube2notion#14]
유저 local 에서 git clone + docker build 하도록 가이드되고 있습니다.
별도 image registry 를 사용하시는 것 같지만,
GitHub actions 에 docker hub public repository 로의 image push 통합으로 사용성을 높였으면 좋겠어요.
제가 해당 repository secrets 설정 등의 권한은 없기에 별도로 요청 드립니다 🙏

**Comment by xissy** [comment]
좋은 의견입니다. 현재 빌드된 도커 이미지를 제 개인 구글 레지스트리에 푸시하고 있는데 docker hub에도 올릴 수 있도록 추가하겠습니다.
