### ISSUE TITLE
repository 라이센스 질문 드립니다.

### ISSUE THREAD

**Issue by gnokoheat** [taehoio/youtube2notion#8]
먼저 좋은 코드를 작성해주셔서 정말 감사하다는 말씀 드립니다.
개인적 필요에따라 해당 repository를 fork해서 코드를 수정하고 재배포 했는데요.
기존 repository 에 어떠한 라이센스도 없는것을 뒤늦게 알게 되었습니다.
코드 수정/재배포를 금지하실 생각이신지 라이센스를 추가하여 권한 명시를 하실 생각이신지 질문 드리고 싶습니다.
기존 코드 수정/재배포 금지에 대한 답변을 주시면 fork 한 repository 는 삭제하도록 하겠습니다.

**Comment by xissy** [comment]
안녕하세요 @gnokoheat 님, 반갑습니다.

아직 라이센스에 대한 고민을 해보지 않았습니다. 별 대단한 내용이 아니기에 fork 하여 수정하는 것에 제한을 둘 마음은 없습니다. 수정 중인 내용을 살펴보았는데 범용적인 개선에 해당하는거 같아요. 코드가 파편화 되는거 보다 이 repo의 codeowner로 등록해 드릴테니 함께 개선해 나가보는건 어떠세요? 재밌을거 같습니다. :)

**Comment by gnokoheat** [comment]
앗 네 빠른답변과 codeowner 로 등록해주셔서 너무 감사드립니다
그럼 해당 repository 에서 추가로 코드작성하는 것으로 기여하도록 하겠습니다!
조심스럽게 라이센스 관련해서는 한가지 말씀을 더 드리자면
youtube, notion 이라는 상업 서비스에 직접 엑세스하는 코드인만큼
해당 코드를 내려받아 사용하는 악의적인 사용자가 발생하는 경우에대한 행위로부터
codeowner 가 책임에 대해 보호받기 위해서라도 MIT, Apache2 등 오픈소스 라이센스 추가를 고려 부탁 드립니다!
그럼 저는 기존에 추가하려 했던 기능들을 해당 repository 에 추가하는 것으로 또 인사드릴께요~

**Comment by xissy** [comment]
@gnokoheat 네 그럼 가장 널널하다고 알려진 MIT 라이센스 추가하는 PR 날리도록 하겠습니다. 👍
